import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { AuthProvider } from "../lib/authContext";
import { SavedProvider } from "../lib/savedContext";
import Head from 'next/head';
import Image from 'next/image';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <AuthProvider>
      <SavedProvider>
        <Head>
          <title>BTV</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/pnlogo.png" />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@600;700&family=Poppins:wght@400;500;600&display=swap" rel="stylesheet" />
        </Head>
        <Image src="https://cfcdn.apowersoft.info/astro/picwish/assets/index-fourth-bg.a19a2877.svg" width="100" height="100" className=' absolute w-1/2 left-1/2 overflow-hidden pointer-events-none opacity-40' alt="bg-img"></Image>
        <Image src="https://cfcdn.apowersoft.info/astro/picwish/assets/index-fourth-bg.a19a2877.svg" width="100" height="100" className=' absolute w-1/3 right-1/3 overflow-hidden pointer-events-none opacity-30 rotate-180' alt="bg-img"></Image>
        <Image src="https://cfcdn.apowersoft.info/astro/picwish/assets/index-fourth-bg.a19a2877.svg" width="100" height="100" className=' absolute w-1/4 left-1/4 overflow-hidden pointer-events-none opacity-10 rotate-45' alt="bg-img"></Image>
        <Component {...pageProps} />
      </SavedProvider>
    </AuthProvider>
  )

}
